<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MHDental</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Ensure the PWA files are copied to the output/publish folder -->
    <None Include="wwwroot\service-worker.js" CopyToOutputDirectory="PreserveNewest" />
    <None Include="wwwroot\manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
